"""phase 2 multi-tenant schema

Revision ID: 91197ea55ea3
Revises: 
Create Date: 2026-08-21 02:36:24.003555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91197ea55ea3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_account_id'), 'audit_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_audit_events_event'), 'audit_events', ['event'], unique=False)
    op.create_index(op.f('ix_audit_events_ts'), 'audit_events', ['ts'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('confirmations',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('order', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('preview', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_index(op.f('ix_confirmations_account_id'), 'confirmations', ['account_id'], unique=False)
    op.create_index(op.f('ix_confirmations_expires_at'), 'confirmations', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_subject'), 'users', ['subject'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('starting_cash', sa.Float(), nullable=False),
    sa.Column('max_order_value', sa.Float(), nullable=False),
    sa.Column('default_product', sa.String(length=8), nullable=False),
    sa.Column('default_exchange', sa.String(length=8), nullable=False),
    sa.Column('live_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('daily_notional_cap', sa.Float(), nullable=False),
    sa.Column('daily_order_cap', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('broker_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('secret_ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('key_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_links_status'), 'broker_links', ['status'], unique=False)
    op.create_index(op.f('ix_broker_links_token_hash'), 'broker_links', ['token_hash'], unique=False)
    op.create_index(op.f('ix_broker_links_user_id'), 'broker_links', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('trading_symbol', sa.String(length=40), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('transaction_type', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('product', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('trigger_price', sa.Float(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_account_id'), 'orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_orders_reference_id'), 'orders', ['reference_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_trading_symbol'), 'orders', ['trading_symbol'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('product', sa.String(length=8), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_account_id'), 'paper_trades', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_trades_symbol'), 'paper_trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trades_symbol'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_account_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_orders_trading_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_reference_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_account_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_broker_links_user_id'), table_name='broker_links')
    op.drop_index(op.f('ix_broker_links_token_hash'), table_name='broker_links')
    op.drop_index(op.f('ix_broker_links_status'), table_name='broker_links')
    op.drop_table('broker_links')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_confirmations_expires_at'), table_name='confirmations')
    op.drop_index(op.f('ix_confirmations_account_id'), table_name='confirmations')
    op.drop_table('confirmations')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_ts'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_account_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
